import React,{useState,useEffect} from 'react';
const money=n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(n);
const labels={STANDARD_MAT:'Thảm tiêu chuẩn',WOODEN_FLOOR:'Sàn gỗ',AVAILABLE:'Hoạt động',MAINTENANCE:'Bảo trì',CLOSED:'Đóng cửa',GOODS:'Hàng hóa',SERVICE:'Dịch vụ'};
const tabs=[['courts','▦','Sân cầu'],['time-slots','◷','Khung giờ & giá'],['categories','◈','Danh mục'],['products','▤','Hàng hóa & dịch vụ']];
const initial={courts:{courtNumber:1,name:'',type:'STANDARD_MAT',status:'AVAILABLE',basePrice:100000},'time-slots':{startTime:'06:00',endTime:'07:00',priceMultiplier:1},categories:{categoryName:''},products:{categoryId:'',name:'',type:'GOODS',unit:'cái',price:0,stockQuantity:0}};
function defaultMultiplier(start,end){return start>='17:00'&&end<='21:00'?1.5:1;}
export default function App(){
 const [session,setSession]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('bcm-session'))}catch{return null}});
 const [tab,setTab]=useState('courts'),[data,setData]=useState({courts:[],'time-slots':[],categories:[],products:[]});
 const [busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('');
 const [modal,setModal]=useState(null),[form,setForm]=useState({}),[fieldErrors,setFieldErrors]=useState({}),[deleteTarget,setDeleteTarget]=useState(null);
 const [credentials,setCredentials]=useState({email:'',password:''}),[quoteCourt,setQuoteCourt]=useState(''),[quote,setQuote]=useState(null);
 function logout(){sessionStorage.removeItem('bcm-session');setSession(null);setData({courts:[],'time-slots':[],categories:[],products:[]});setModal(null);setDeleteTarget(null);}
 async function api(path,method='GET',body,token=session?.accessToken){
  const res=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});
  let json;try{json=await res.json()}catch{throw new Error('Không thể đọc phản hồi máy chủ. Kiểm tra backend.');}
  if(!res.ok||!json.success){if(res.status===401){logout();}const e=new Error(json.message||'Không thực hiện được thao tác');e.fields=json.data;throw e;}return json.data;
 }
 async function load(){setBusy(true);setError('');try{const values=await Promise.all(tabs.map(([key])=>api('/admin/'+key)));setData(Object.fromEntries(tabs.map(([key],i)=>[key,values[i]])));}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{if(session)load()},[session]);
 useEffect(()=>{setQuery('');setFilter('');setNotice('');setQuote(null)},[tab]);
 async function login(e){e.preventDefault();setSaving(true);setError('');try{const s=await api('/auth/login','POST',credentials,null);if(!s.user?.roles?.includes('ADMIN'))throw new Error('Tài khoản cần quyền ADMIN để sử dụng trang quản trị.');sessionStorage.setItem('bcm-session',JSON.stringify(s));setSession(s);setCredentials({email:'',password:''})}catch(e){setError(e.message)}finally{setSaving(false)}}
 function open(item=null){setModal({id:item?.id||null});setForm(item?{...item}:{...initial[tab],...(tab==='courts'?{courtNumber:Math.max(0,...data.courts.map(c=>c.courtNumber))+1}:{}),...(tab==='products'?{categoryId:data.categories[0]?.id||''}:{})});setFieldErrors({});setError('');}
 function change(key,value){setForm(old=>{const next={...old,[key]:value};if(tab==='products'&&key==='type'&&value==='SERVICE')next.stockQuantity=0;if(tab==='time-slots'&&(key==='startTime'||key==='endTime'))next.priceMultiplier=defaultMultiplier(next.startTime.slice(0,5),next.endTime.slice(0,5));return next});}
 async function save(e){e.preventDefault();setSaving(true);setFieldErrors({});setError('');try{let payload={...form};for(const key of ['courtNumber','basePrice','priceMultiplier','price','stockQuantity'])if(key in payload)payload[key]=Number(payload[key]);await api('/admin/'+tab+(modal.id?'/'+modal.id:''),modal.id?'PUT':'POST',payload);setModal(null);setNotice('Đã lưu dữ liệu thành công.');await load()}catch(e){setError(e.message);if(e.fields&&typeof e.fields==='object')setFieldErrors(e.fields)}finally{setSaving(false)}}
 async function remove(){setSaving(true);setError('');try{await api('/admin/'+tab+'/'+deleteTarget.id,'DELETE');setDeleteTarget(null);setNotice('Đã xóa dữ liệu thành công.');await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 const rows=data[tab].filter(x=>{const text=[x.name,x.categoryName,x.courtNumber,x.startTime,x.endTime,labels[x.type],labels[x.status]].join(' ').toLocaleLowerCase('vi');return text.includes(query.toLocaleLowerCase('vi'))&&(!filter||(tab==='products'?x.categoryId===filter:x.status===filter))});
 const title=tabs.find(([k])=>k===tab)[2];
 function field(key,label,type='text',extra={}){return <label className="field" key={key}>{label}<input aria-label={label} name={key} type={type} value={form[key]??''} onChange={e=>change(key,e.target.value)} required {...extra}/>{fieldErrors[key]&&<small className="invalid">{fieldErrors[key]}</small>}</label>}
 function select(key,label,options){return <label className="field" key={key}>{label}<select aria-label={label} name={key} value={form[key]??''} onChange={e=>change(key,e.target.value)} required>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{fieldErrors[key]&&<small className="invalid">{fieldErrors[key]}</small>}</label>}
 if(!session)return <div className="login-layout"><section className="login-story"><div className="brand">BCM<span>COURT MANAGEMENT</span></div><div><span className="eyebrow">KHÔNG GIAN QUẢN TRỊ</span><h1>Mọi sân chơi.<br/>Một nơi quản lý.</h1><p>Quản lý sân, khung giờ và danh mục hàng hóa<br/>để vận hành câu lạc bộ mỗi ngày.</p><div className="court-illustration"><i/><b/></div></div><small>BADMINTON COURT MANAGEMENT</small></section><section className="login-panel"><form onSubmit={login}><span className="eyebrow">CHÀO MỪNG TRỞ LẠI</span><h2>Đăng nhập quản trị</h2><p className="muted">Sử dụng tài khoản có quyền Admin của bạn.</p><label className="field">Email<input type="email" required autoComplete="username" value={credentials.email} onChange={e=>setCredentials({...credentials,email:e.target.value})}/></label><label className="field">Mật khẩu<input type="password" required autoComplete="current-password" value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})}/></label>{error&&<div role="alert" className="alert error">{error}</div>}<button className="primary wide" disabled={saving}>{saving?'Đang đăng nhập…':'Đăng nhập →'}</button></form></section></div>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand">BCM<span>COURT MANAGEMENT</span></div><span className="nav-caption">QUẢN LÝ DỮ LIỆU</span><nav>{tabs.map(([key,icon,label])=><button key={key} className={tab===key?'nav active':'nav'} onClick={()=>setTab(key)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-bottom"><div className="avatar">A</div><div><strong>{session.user?.fullName||'Quản trị viên'}</strong><small>Administrator</small></div><button aria-label="Đăng xuất" title="Đăng xuất" onClick={logout}>↗</button></div></aside><main><header className="topbar"><span>Vận hành / <strong>{title}</strong></span><span className="live"><i/> Web Admin</span><button className="mobile-logout secondary" onClick={logout}>Đăng xuất</button></header><div className="workspace"><div className="page-heading"><div><span className="eyebrow">MASTER DATA</span><h1>{title}</h1><p className="muted">{tab==='courts'?'Theo dõi và cấu hình hệ thống sân của câu lạc bộ.':tab==='time-slots'?'Thiết lập giờ chơi và hệ số giá theo từng khung giờ.':tab==='categories'?'Tổ chức hàng hóa và dịch vụ theo danh mục.':'Quản lý thông tin bán hàng và tồn kho ban đầu.'}</p></div><button className="primary" onClick={()=>open()} disabled={busy||(tab==='products'&&!data.categories.length)}>＋ {tab==='courts'?'Thêm sân':tab==='time-slots'?'Thêm khung giờ':tab==='categories'?'Thêm danh mục':'Thêm sản phẩm'}</button></div>
 <div className="stats"><div><span>Tổng số sân</span><strong>{data.courts.length.toString().padStart(2,'0')}</strong><small>Trong hệ thống</small></div><div><span>Sân hoạt động</span><strong>{data.courts.filter(c=>c.status==='AVAILABLE').length.toString().padStart(2,'0')}</strong><small className="green">Sẵn sàng phục vụ</small></div><div><span>Khung giờ</span><strong>{data['time-slots'].length.toString().padStart(2,'0')}</strong><small>Cấu hình trong ngày</small></div><div><span>Hàng hóa & dịch vụ</span><strong>{data.products.length.toString().padStart(2,'0')}</strong><small>{data.categories.length} danh mục</small></div></div>
 {error&&!modal&&!deleteTarget&&<div role="alert" className="alert error">{error} <button onClick={load}>Thử lại</button></div>}{notice&&<div role="status" className="alert success">{notice}</div>}
 <section className="content-panel"><div className="toolbar"><label className="search"><span>⌕</span><input aria-label="Tìm kiếm" placeholder="Tìm kiếm…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{tab==='courts'&&<select aria-label="Lọc trạng thái" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Tất cả trạng thái</option>{['AVAILABLE','MAINTENANCE','CLOSED'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select>}{tab==='products'&&<select aria-label="Lọc danh mục" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Tất cả danh mục</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.categoryName}</option>)}</select>}<span className="count">{rows.length} kết quả</span><button className="secondary" onClick={load} disabled={busy}>↻ Làm mới</button></div>
 {busy?<div className="empty" role="status">Đang tải dữ liệu…</div>:rows.length===0?<div className="empty"><span>◇</span><h3>{query||filter?'Không tìm thấy kết quả':'Chưa có dữ liệu'}</h3><p>{tab==='products'&&!data.categories.length?'Tạo danh mục trước khi thêm sản phẩm.':'Thêm dữ liệu mới hoặc thay đổi bộ lọc để tiếp tục.'}</p></div>:tab==='courts'?<div className="court-grid">{rows.map(c=><article className="court-card" key={c.id}><div className="card-top"><span className={'badge '+c.status}>{labels[c.status]}</span><span className="court-number">#{String(c.courtNumber).padStart(2,'0')}</span></div><div className={'court-drawing '+(c.status!=='AVAILABLE'?'dim':'')}><div/><i/><b/></div><h3>{c.name}</h3><p className="muted">{labels[c.type]}</p><div className="card-bottom"><div><strong>{money(c.basePrice)}</strong><small>Giá gốc / khung giờ</small></div><div className="actions"><button onClick={()=>open(c)}>Sửa</button><button className="danger" onClick={()=>{setError('');setDeleteTarget(c)}}>Xóa</button></div></div></article>)}</div>:<div className="table-scroll"><table><thead><tr>{(tab==='time-slots'?['Khung giờ','Hệ số giá','Phân loại']:tab==='categories'?['Tên danh mục','Số sản phẩm']:['Tên sản phẩm','Danh mục','Loại','Đơn vị','Giá niêm yết','Tồn kho']).map(h=><th key={h}>{h}</th>)}<th>Thao tác</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}>{tab==='time-slots'?<><td><strong>{x.startTime.slice(0,5)} — {x.endTime.slice(0,5)}</strong></td><td><span className={'badge '+(x.priceMultiplier>1?'MAINTENANCE':'AVAILABLE')}>×{Number(x.priceMultiplier).toFixed(2)}</span></td><td>{x.priceMultiplier>1?'Giá cao điểm':'Giá thông thường'}</td></>:tab==='categories'?<><td><strong>{x.categoryName}</strong></td><td>{data.products.filter(p=>p.categoryId===x.id).length}</td></>:<><td><strong>{x.name}</strong></td><td>{data.categories.find(c=>c.id===x.categoryId)?.categoryName||'—'}</td><td><span className="badge neutral">{labels[x.type]}</span></td><td>{x.unit}</td><td>{money(x.price)}</td><td>{x.type==='SERVICE'?'—':x.stockQuantity}</td></>}<td><div className="actions"><button onClick={()=>open(x)}>Sửa</button><button className="danger" onClick={()=>{setError('');setDeleteTarget(x)}}>Xóa</button></div></td></tr>)}</tbody></table></div>}
 </section>
 {tab==='time-slots'&&<section className="price-panel"><div><span className="eyebrow">KIỂM TRA BẢNG GIÁ</span><h3>Giá sân theo khung giờ</h3><p className="muted">Giá gốc × hệ số. Khung giờ có thể cấu hình riêng.</p></div><div className="quote-controls"><select aria-label="Chọn sân tính giá" value={quoteCourt} onChange={e=>{setQuoteCourt(e.target.value);setQuote(null)}}><option value="">Chọn sân hoạt động</option>{data.courts.filter(c=>c.status==='AVAILABLE').map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><select aria-label="Chọn khung giờ tính giá" value={quote?.timeSlotId||''} onChange={async e=>{setError('');const id=e.target.value;if(!id){setQuote(null);return}try{setQuote(await api('/public/price-quote?courtId='+quoteCourt+'&timeSlotId='+id))}catch(err){setError(err.message)}}} disabled={!quoteCourt}><option value="">Chọn khung giờ</option>{data['time-slots'].map(s=><option key={s.id} value={s.id}>{s.startTime.slice(0,5)} – {s.endTime.slice(0,5)}</option>)}</select>{quote&&<strong className="quote-value">{money(quote.basePrice)} × {quote.priceMultiplier} = {money(quote.price)}</strong>}</div></section>}
 </div><footer>BCM · Master Data <span>Sân cầu · Khung giờ · Danh mục · Hàng hóa</span></footer></main>
 {modal&&<div className="overlay"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="dialog-head"><h2 id="dialog-title">{modal.id?'Chỉnh sửa':'Thêm mới'} · {title}</h2><button aria-label="Đóng" disabled={saving} onClick={()=>{setModal(null);setError('')}}>✕</button></div><form onSubmit={save}><div className="form-grid">{tab==='courts'?<>{field('courtNumber','Số sân','number',{min:1,step:1})}{field('name','Tên sân','text',{maxLength:255})}{select('type','Loại sân',['STANDARD_MAT','WOODEN_FLOOR'].map(v=>[v,labels[v]]))}{select('status','Trạng thái',['AVAILABLE','MAINTENANCE','CLOSED'].map(v=>[v,labels[v]]))}{field('basePrice','Giá gốc (VNĐ / khung giờ)','number',{min:0,max:99999999.99,step:0.01})}</>:tab==='time-slots'?<>{field('startTime','Giờ bắt đầu','time')}{field('endTime','Giờ kết thúc','time')}{field('priceMultiplier','Hệ số giá','number',{min:0.01,max:9.99,step:0.01})}<p className="form-help">Mặc định 17:00–21:00 ×1.5, giờ khác ×1.0. Có thể điều chỉnh hệ số riêng. Khung giờ không được chồng lấn.</p></>:tab==='categories'?field('categoryName','Tên danh mục','text',{maxLength:255}):<>{field('name','Tên hàng hóa / dịch vụ','text',{maxLength:255})}{select('categoryId','Danh mục',data.categories.map(c=>[c.id,c.categoryName]))}{select('type','Loại',['GOODS','SERVICE'].map(v=>[v,labels[v]]))}{field('unit','Đơn vị tính','text',{maxLength:50})}{field('price','Giá niêm yết (VNĐ)','number',{min:0,max:99999999.99,step:0.01})}{field('stockQuantity',modal.id?'Tồn kho hiện tại':'Tồn ban đầu','number',{min:0,max:2147483647,step:1,disabled:!!modal.id||form.type==='SERVICE'})}<p className="form-help">Tồn ban đầu chỉ nhập khi tạo sản phẩm. Dịch vụ không theo dõi tồn kho. Điều chỉnh tồn sau này thuộc phân hệ kho.</p></>}</div>{error&&<div className="alert error" role="alert">{error}</div>}<div className="dialog-foot"><button type="button" className="secondary" disabled={saving} onClick={()=>{setModal(null);setError('')}}>Hủy</button><button className="primary" disabled={saving}>{saving?'Đang lưu…':'Lưu thay đổi'}</button></div></form></section></div>}
 {deleteTarget&&<div className="overlay"><section className="dialog small" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">Xóa dữ liệu?</h2><p>Bạn muốn xóa <strong>{deleteTarget.name||deleteTarget.categoryName||deleteTarget.startTime+' – '+deleteTarget.endTime}</strong> khỏi danh sách?</p><p className="muted">Hệ thống sẽ kiểm tra các dữ liệu liên quan trước khi thực hiện.</p>{error&&<div className="alert error" role="alert">{error}</div>}<div className="dialog-foot"><button className="secondary" disabled={saving} onClick={()=>{setDeleteTarget(null);setError('')}}>Hủy</button><button className="primary delete" disabled={saving} onClick={remove}>{saving?'Đang xóa…':'Xác nhận xóa'}</button></div></section></div>}
 </div>;
}
